#!/bin/sh

log() {
    logger --id="${AUTORIP_PID:-${$}}" -t "Autorip" "${1}"
}

notify() {
    urgency="${1}"
    title="${2}"
    if [ -z "${3}" ]
    then
        ssh sapeint@192.168.1.250 "DISPLAY=:0 notify-send --urgency=${urgency} '${title}'"
    else
        ssh sapeint@192.168.1.250 "DISPLAY=:0 notify-send --urgency=${urgency} '${title}' '${3}'"
    fi
}


if [ -z  "${NAME}" ] && [ -z "${1}" ]
then
    printf "Var NAME not defined!\n" 1>&2
    exit 1
elif [ -n "${1}" ] && [ -z "${NAME}" ]
then
    NAME="${1}"
fi

if [ -z "${TARGET_DIR}" ] && [ -z "${2}" ]
then
    TARGET_DIR="/home/ps2/roms/verified/DVD"
elif [ -n "${2}" ] && [ -z "${TARGET_DIR}" ]
then
    TARGET_DIR="${2}"
fi

if [ -z "${REJECT_DIR}" ] && [ -z "${3}" ]
then
    REJECT_DIR="/home/ps2/roms/rejected"
elif [ -n "${3}" ] && [ -z "${REJECT_DIR}" ]
then
    REJECT_DIR="${3}"
fi

checkres() {
    err="${1}"
    if [ "${err}" -ne 0 ]
    then
        exit "${err}"
    fi
}

sizes=$(isosize -x /dev/sr0 2>&1)
e="${?}"
checkres "${e}"
sector_count=$(echo ${sizes} | sed -e 's/.* \(.*\),.*/\1/')
sector_size=$(echo ${sizes} | sed -e 's/.*,.*: \(.*\)/\1/')
printf "sector count: %s, sector size: %s\n" "${sector_count}" "${sector_size}"
log "sector count: ${sector_count}, sector size: ${sector_size}"

biF="1024"
bF="1000"
GiB=$(dc -e "3 k ${sector_size} ${sector_count} * ${biF} / ${biF} / ${biF} / p")
GB=$(dc -e "3 k ${sector_size} ${sector_count} * ${bF} / ${bF} / ${bF} / p")
printf "Final ISO Size: ${GB} GB, ${GiB} GiB\n"
log "Final ISO Size: ${GB} GB, ${GiB} GiB"
dd if=/dev/sr0 of="/home/ps2/${NAME}.iso" bs="${sector_size}" count="${sector_count}" status=progress

log "Done, sending notification"
# ssh sapeint@192.168.1.250 'DISPLAY=:0 notify-send --urgency=critical "Disc Rip Done!" "Your Disc Rip has completed, but needs to be checked!"'
notify "critical" "Disc Rip Done!" "Your Disc Rip has been completed, but needs to be checked"
log "Done, checking message"
burnt_md5=$(md5sum "/home/ps2/${NAME}.iso")
disk_md5=$(dd if=/dev/sr0 bs="${sector_size}" count="${sector_count}" | md5sum)

compare_hashes() {
    # NOTE: This is a bit of a hack, we use field splitting
    #  to split a part the md5sum results and compare only the hashes.
    log "Burnt md5: ${1}"
    log "Disk md5: ${3}"
    [ "${1}" = "${3}" ]
    return $?
}

IFS=' '
if compare_hashes ${burnt_md5} ${disk_md5}
then
    mv "/home/ps2/${NAME}.iso" "${TARGET_DIR}/${NAME}.iso"
    notify "low" "Disc Rip Done!" "Your Disc Rip has completed!"
    # ssh sapeint@192.168.1.250 'DISPLAY=:0 notify-send --urgency=low "Disc Rip Done!" "Your Disc Rip has completed!"'
    exit 0
else
    mv "/home/ps2/${NAME}.iso" "${REJECT_DIR}/${NAME}.iso"
    notify "critical" "Disc Rip Failure!" "Your Disc Rip has failed!\nDisc Name: ${NAME}"
    # ssh sapeint@192.168.1.250 'DISPLAY=:0 notify-send --urgency=critical "Disc Rip Failure!" "Your Disc Rip has failed!\nDisc Name: '"${NAME}"'"'
    exit 1
fi
